# Generated by Django 6.0 on 2025-12-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie')),
                ('critical', models.BooleanField(default=False, verbose_name='Equipo Crítico')),
                ('installed_at', models.DateField(verbose_name='Fecha de Instalación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='maintenance.empresa', verbose_name='Empresa Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('frequency_days', models.PositiveIntegerField(verbose_name='Frecuencia (días)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='maintenance.equipo', verbose_name='Equipo Asociado')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Trabajo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='maintenance.equipo', verbose_name='Equipo')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='maintenance.planmantencion', verbose_name='Plan de Mantención')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='maintenance.tecnico', verbose_name='Técnico Asignado')),
            ],
        ),
    ]
